export const rewardScrollImages = {
	gv: require('./gv-logo.png'),
	apple: require('./apple-logo.png'),
	sephora: require('./sephora-logo.png'),
	gap: require('./gap-logo.png'),
	nike: require('./nike-logo.png'),
	forever: require('./forever21-logo.png'),
	starbucks: require('./starbucks-logo.png'),
	groupon: require('./groupon-logo.png'),
	foodpanda: require('./foodpanda-logo.png'),
	zara: require('./zara-logo.png'),
	beats: require('./beats-logo.png'),
	underarmour: require('./underarmour-logo.png'),
	adidas: require('./adidas-logo.png'),
	uber: require('./uber-logo.png'),
	expedia: require('./expedia-logo.png'),
	grab: require('./grab-logo.png'),
	hnm: require('./hnm-logo.png'),
	watsons: require('./watsons-logo.png'),
	uniqlo: require('./uniqlo-logo.png'),
	dintaifung: require('./dintaifung-logo.png'),
	ikea: require('./ikea-logo.png'),
	carousell: require('./carousell-logo.png'),
	citi: require('./citi-logo.png'),
	bolt: require('./bolt-icon.png'),
	piggy: require('./piggy-icon.png'),
};

export const rewardCardImages = {
	appleBg: require('./apple-bg.png'),
	forever21Bg: require('./forever21-bg.png'),
	zaraBg: require('./zara-bg.png'),
	beatsBg: require('./beats-bg.png'),
	adidasBg: require('./adidas-bg.png'),
	uberBg: require('./uber-bg.png'),
	expediaBg: require('./expedia-bg.png'),
	underarmourBg: require('./underarmour-bg.png'),
	grabBg: require('./grab-bg.png'),
	hnmBg: require('./hnm-bg.png'),
	watsonsBg: require('./watsons-bg.png'),
	zaloraBg: require('./zalora-bg.png'),
	glintsBg: require('./glints-bg.png'),
	ezBg: require('./ez-bg.png'),
	uniqloBg: require('./uniqlo-bg.png'),
	deliverooBg: require('./deliveroo-bg.png'),
};